[package]
name = "leaf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libleaf = { path = "./libleaf" }
pretty_env_logger = "0.4.0"
